# Set up
Need tensorflow==2.18.0 
- (tensorflow-gpu and tensorflow are the same package since the release of version 2.1. Installing tensorflow alone will enable GPU acceleration.)

pip install tensorflow
* TensorFlow is an open source ML framework for all developers. It is used for implementing ML and deep learning applications.
* Google team created TensorFlow.
* official site www.tensorflow.org
* Flexibility: TensorFlow caters to diverse ML tasks, encompassing image recognition, natural language processing (NLP), and recommender systems.
* Scalability: Seamlessly handle large datasets and complex models on various hardware platforms, from single machines to powerful TPUs (Tensor Processing Units) in the cloud.
* Open-Source Community: Benefit from a vibrant community of developers, extensive documentation, and a plethora of tutorials and resources to expedite your learning.
* TensorBoard Visualization: TensorBoard, a built-in visualization suite, aids in monitoring model training progress, analyzing performance metrics, and debugging issues.* TensorFlow is well-documented and includes plenty of machine learning libraries
* TensorFlow offers two primary interfaces for building ML models:

1. Keras: A high-level API ideal for beginners and rapid prototyping. Keras abstracts away complexities, enabling you to focus on model design and experimentation.

2. TensorFlow Core API: A low-level, more granular approach offering finer control over model architecture and computations. This is preferred for experienced developers or situations requiring extensive customization.


TensorFlow is based on the idea of tensors. A tensor is a generalization of scalars, vectors, and matrices. You can think of it as a multi-dimensional array.

- A scalar is a single number (0D tensor).
- A vector is a one-dimensional array (1D tensor).
- A matrix is a two-dimensional array (2D tensor).
- Tensors with more than two dimensions are higher-order tensors (e.g., 3D, 4D).
TensorFlow uses a computational graph to execute operations, where nodes represent operations and edges represent data (tensors) flowing between them.

## Hello World


In [1]:
import tensorflow as tf
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!


## GPU installed ?
Check if GPU is available

In [3]:
import tensorflow as tf
print('TensorFlow version - ',tf.__version__)
# Check if GPU is available
gpu_available = tf.config.list_physical_devices('GPU')

if gpu_available:
    print("TensorFlow is installed as GPU version.")
else:
    print("TensorFlow is installed as CPU version.")

TensorFlow version -  2.18.0
TensorFlow is installed as CPU version.


## Eager Execution
In TensorFlow 2.x, eager execution is enabled by default, meaning operations are evaluated immediately. This is in contrast to the previous version (v1.x), where operations were added to a computational graph and executed only when a session was run.

To check if eager execution is enabled in your environment, you can run this code:

In [12]:
print("Eager execution enabled:", tf.executing_eagerly())


Eager execution enabled: True


In [6]:
import tensorflow as tf

# Scalar (0D tensor)
scalar = tf.constant(5)
print("Scalar:", scalar)

# Vector (1D tensor)
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

# Matrix (2D tensor)
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

# 3D Tensor
tensor_3d = tf.constant([[[1], [2]], [[3], [4]]])
print("3D Tensor:", tensor_3d)


Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor: tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


## TensorFlow Variables
In TensorFlow, Variables are used to store and update values during the training process. Unlike constants, they are mutable and can be updated.

In [13]:
import tensorflow as tf

# Create a variable initialized to 0
var = tf.Variable(0, dtype=tf.int32)
print("Initial Variable:", var.numpy())

# Update the variable by adding 5
var.assign_add(5)
print("Updated Variable:", var.numpy())


Initial Variable: 0
Updated Variable: 5


## Basic operations
TensorFlow allows you to perform various mathematical operations on tensors.

In [9]:
# Addition
tensor_add = tf.add(vector, [4, 5, 6])
print("Addition of vector:", tensor_add)

# Multiplication
tensor_mult = tf.multiply(vector, 3)
print("Multiplication of vector by 3:", tensor_mult)

# Matrix multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
matrix_mult = tf.matmul(matrix_a, matrix_b)
print("Matrix multiplication result:\n", matrix_mult)


Addition of vector: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Multiplication of vector by 3: tf.Tensor([3 6 9], shape=(3,), dtype=int32)
Matrix multiplication result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## TensorFlow Functions and Control Flow
You can define functions in TensorFlow to apply transformations or operations repeatedly. TensorFlow provides control flow operations like tf.while_loop, tf.cond, etc., for conditional operations.

Example (Conditional execution using tf.cond):

In [14]:
import tensorflow as tf

def conditional_example(x):
    # tf.cond allows conditional execution based on a condition
    return tf.cond(x > 0, lambda: x * 2, lambda: x - 2)

# Test with positive value
print("Result with positive x (5):", conditional_example(tf.constant(5)).numpy())

# Test with negative value
print("Result with negative x (-3):", conditional_example(tf.constant(-3)).numpy())


Result with positive x (5): 10
Result with negative x (-3): -5
